### ISSUE TITLE
Screen sample code draw a wrong line

### ISSUE THREAD

**Issue by clang-clang-clang** [SpyricGames/Solar2D-Plugins-Public#1]
Thank you for the good plugins.

Here, 

https://github.com/SpyricGames/Solar2D-Plugins-Public/blob/0b0e4763d7f992932a157d298d706a6271be489c/Screen/main.lua#L62

should use `screen.safe.minY` instead of `screen.minY`, isn't it?

Test in portrait orient (comment out `orientation` in `build.settings`) produce:

![Screenshot_20220726_195547_com coronalabs Screen](https://user-images.githubusercontent.com/53489032/181001426-24a1fcdc-7ee5-43eb-b869-00acc14f6a10.jpg)

**Comment by XeduR** [comment]
Thanks for the heads up. I'll fix it in a moment.

**Comment by XeduR** [comment]
Fixed with [8af950e](https://github.com/SpyricGames/Solar2D-Plugins-Public/commit/8af950ec0f31ee8c0b71c60c33e9059aef281bb8).
